### PR TITLE
Add and persist marker

### PR DESCRIPTION
**Pull request by nicsaal**
Changes to be tested. I added code to:
1)Place a custom marker on map with a long press gesture.
2)Used sharedPreferences to store/retrieve key value pairs.
3)Updated OnCreate and OnMapReady to check for stored values.
Oh...and merged amazonMaster into branch.

### CODE REVIEW

**Comment by oliversaal** [comment]
This design is not exactly what you want. You have to think about this as an object or class since we're going to add custom markers depending on the app. Think about a marker for a gatsby or a marker to indicate your friend's location. A class and its derived classes will support that design.

Secondly, this implementation needs to cleanup - I noticed several bugs in it and also redundancies that we can clean up. Let's revisit the AmazonMaps example and see how they designed theirs so we can leverage the best of both worlds (Amazon and Google) for our markers. I assume we'll publish the same custom marker update to both appstores.

**Comment by oliversaal** [comment]
Are you closing out this PR to be replaced with something common to both appstores?

**Comment by oliversaal** [comment]
I still think you missed the point of the design. All you did differently was add a Fetcher class. 

If you used the AmazonMap's CoffeeShop example as a foundation, you will notice that they created a CoffeeShop class at the heart of their design.  The fetcher would fetch a collection of CoffeeShops. 

With this design, you could spawn children "shops" such as a GatsbyShop or KiteShop or SurfShop and expand your app with new pins for each shop type. You would also have added ability to store custom information about each shop so that users could drill down into it for more details (e.g. address, pictures, phone numbers, leaderboard, etc).

I'm going to start a new branch - fork it from Amazon - since we need that compatibility as well and then merge it into master eventually. Take a look at it to see the difference in approaches. The sharedPreference or localStorage is still something we can leverage but you used a Map<String, ?> while only using the value but not the key. I wonder if that's the best approach.

**Comment by nicsaal** [comment]
Thanks for the feedback.

**Comment by nicsaal** [comment]
Abandoning PR as we will be a taking a different approach to this which makes use of a better design.

**Pull request closed without merging**
